<template>
  <HeroTextImage
    title="Financial Accounting and Reporting"
    description="Financial control depends on every core event being reflected
          accurately in the books. Arkam links operational activity to a
          multi-entity, multi-currency accounting framework that provides
          real-time visibility for finance and risk teams."
    :button-one="{ link: '/', text: 'Book a Live Demo' }"
    :button-two="{ link: '/', text: 'Contact us' }"
    image="/images/financial-accounting-and-reporting.webp"
  />
  <SectionTextListImage
    title="Key Points"
    :items="keyPoints"
    image="/images/financial-accounting-key-points.webp"
    :darkImage="true"
  />

  <SectionTextList
    title="FAQ"
    description="Short answers to how Arkam Core fits into your architecture, security model and roadmap."
    :items="faq"
  />

  <ArkamCoreBankingInAction />
</template>

<script setup>
import HeroTextImage from "../../../components/hero/HeroTextImage.vue";
import SectionTextListImage from "../../../components/sections/SectionTextListImage.vue";
import SectionTextList from "../../../components/sections/SectionTextList.vue";
import SectionCTABanner from "../../../components/sections/SectionCTABanner.vue";

const keyPoints = [
  {
    title: "Integrated General Edger",
    description:
      "A general ledger designed to receive postings from the core, with support for multiple entities and currencies.",
  },
  {
    title: "Configurable Chart of Accounts",
    description:
      "Map products, fees and events to your chart of accounts. As you introduce new propositions, mappings can be extended without redesigning the entire ledger.",
  },
  {
    title: "Real-Time Postings",
    description:
      "Events generated by the core are posted in real time, reducing reliance on batch reconciliation and manual corrections.",
  },
  {
    title: "Regulatory and Management Reporting",
    description:
      "Data from the accounting layer supports regulatory, management and statutory reports, with the ability to drill down to transaction level where required.",
  },
  {
    title: "Full Audit Trail",
    description:
      "Postings, adjustments and reversals are logged with user and timestamp information, simplifying internal and external audits.",
  },
];

const faq = [
  {
    title: "Does Arkam include an integrated General Ledger (GL)?",
    description:
      "Yes. Arkam includes an integrated general ledger designed to receive postings from core banking events, with support for multi-entity and multi-currency operations.",
  },
  {
    title: "Can we map Arkam postings to our chart of accounts?",
    description:
      "Yes. Arkam supports a configurable chart of accounts mapping so products, fees and events can be aligned to your accounting structure. As you introduce new propositions, mappings can be extended without redesigning the ledger.",
  },
  {
    title: "Are postings real-time or batch-based?",
    description:
      "Arkam supports real-time postings. Core events are posted as they occur, reducing reliance on batch reconciliation and limiting manual corrections.",
  },
  {
    title: "What reporting does the accounting layer support?",
    description:
      "The accounting layer supports regulatory, management and statutory reporting needs by providing structured accounting data with the ability to drill down to transaction-level detail where required.",
  },
];
</script>

<style lang="scss" scoped></style>
